### ISSUE TITLE
equivalent to    source(somepackage, local = TRUE)

### ISSUE THREAD

**Issue by vnijs** [smbache/import#4] opened 2015-04-01 18:11 UTC
I really like the idea of bringing python's import functionality to R. Thanks!

Question: Does the import function have an option to evaluate functions in a particular environment? I would like to use it in a Shiny app where some functions need to be evaluated in the 'shiny' environment.

Also, python import allows wildcards. Is that an option?

**Comment by smbache** [comment] 2015-04-01 18:23
For the first part, I'm not sure I understand exactly what you want. Could you you give an explicit example?

For the second; I've considered that and I'm still unsure — pro is that it could make multiple imports more compact, and con is that it may go slightly against the principle of making explicit what is being imported from which package. Not sure what is more important (in the extreme case, `import::from(pkg, "*")` would be Jo clearer than `library(pkg)`. 

In some cases, however, it would still be clear enough, say `import::from(ensurer, "ensure*")`.

**Comment by smbache** [comment] 2015-04-01 19:16
You can do `import::here(foo, .from = bar)`, would this be what you want? You can do this in a function, env, or wherever.

**Comment by vnijs** [comment] 2015-04-02 00:48
Thanks for the input Stefan. FYI for the CRAN version I had to use import::here(.from, ...) rather than import::here(..., .from). A typo in the manual? 

In shiny apps, if you want to split code across multiple files, you use source(‘foo.R’, local = TRUE) inside server.R so the functions are evaluated in the right environment. 

I turned my app ([vnijs/radiant](https://github.com/vnijs/radiant)) into an R-package recently. There are some functions that need to be evaluated in the shiny environment. However, I prefer to keep these functions in the R/ directory and document and test them as usual. 

As a smaller example, below a link to a shiny app with functionality that @jcheng5 and I have been talking about. It maintains state on browser-refresh and can be used to save (or share) state. Radiant already has some of this functionality but Joe's approach works better with Shiny Server.

The source and import lines are here:
https://github.com/vnijs/shiny-resume/blob/master/inst/test/server.R#L11-L18

The relevant functions are in:
https://github.com/vnijs/shiny-resume/blob/master/R/state.R

When trying import::here, however, the r_state variable is not found. This does work when using source("../../R/state.R", local = TRUE). FYI r_state is a list with app settings derived from input.

Any suggestions/comments would be very welcome

**Comment by smbache** [comment] 2015-04-02 06:31
OK I'll look into it when I have some spare time. In the meantime, if you figure it out let me know. 
I'm sure youre right, but I'm not sure why it does not already work as you want, as it's basically just local assignment. 

Wrt `import::here` everywhere I look it's `import::here(..., .from)`. Weird?

**Comment by smbache** [comment] 2015-04-02 06:41
Could you try explicitly naming the `.from` argument? It is required in the `here` formulation; i.e.

```R
import::here(state_init, state_single, state_multiple, .from = resume)

#OR 

import::here(.from = resume, state_init, state_single, state_multiple)
```

**Comment by vnijs** [comment] 2015-04-02 07:40
import does not give errors with any of the following:

  import::here(resume, state_init, state_single, state_multiple)
  import::here(.from = resume, state_init, state_single, state_multiple)
  import::here(state_init, state_single, state_multiple, .from = resume)

I was able to simplify the example substantially and still illustrate the question I have. If you install:
devtools::install_github("vnijs/shiny-resume")

and then run [test.R](https://github.com/vnijs/shiny-resume/blob/master/inst/test/test.R) you will see the issue. The function cannot find r_state when using import but can when using source(  , local = TRUE).

**Comment by smbache** [comment] 2015-04-02 07:41
Ok — I'm on the road but will have a look when able.

**Comment by smbache** [comment] 2015-04-02 14:38
I see the reason why `here` works without specifying `.from` as long as it's the first argument. It's not intended to work, though, and I should rewrite this. Haven't yet had a chance to look at your issue though...

**Comment by smbache** [comment] 2015-04-02 18:19
Now, after reading your test.R script, I understand what the problem is. When you `source` the function definition, it is as if you write the function where the `source` command is, and the enclosing environment will include whatever is there, here `r_state`. When you import a function (even as simply as `obj <- pkg::obj`) the function's enclosing environment is the package namespace, and `r_state` will be unknown to `state_init`.

It would be possible (I even tried) to make a copy of the function definition, rather than importing it, BUT:

* I can't think of many use cases (except for this one), and in many cases the function will break if it depends on anything in its namespace
* I think it would be better practice to make the functions in a package self-contained. You could do this by passing `r_state` as an argument.

Let me know if this makes sense, and if you agree.

PS, I added checks to make `import::here` require the `.from` argument explicitly to avoid any confusion.

**Comment by vnijs** [comment] 2015-04-02 18:40
Ah. So there is no real equivalent for source( , local = TRUE) for exported (imported) functions. Too bad.

I could indeed pass r_state as an argument but (1) one of the state_* functions is called for every input in the app, (2) r_state is the only list used, and (3) the state_* functions are called inside another function call (e.g., selectInput) so repeating state_init( , , r_state) is annoying, to me at least :) 

I agree that this main only be really relevant for Shiny apps. Thanks for your input and time!

**Comment by smbache** [comment] 2015-04-02 18:51
No worries. 

Well, it's easy to make a function that imports the way you want; I'm just unsure whether it's a good idea to include in this package.

I'd show you how if you want, and maybe I'll think some more about it.

**Comment by vnijs** [comment] 2015-04-02 19:09
You may be right that this is not a good idea. It might be best to have the functionality built into the Shiny input functions but that may be difficult (see this [thread](https://github.com/jcheng5/shiny-resume/pull/1). 

I would still very much like to know how to do this. Using source with local = TRUE is common in Shiny apps (and mentioned in Rstudio tutorials) so why have something similar not for package/exported functions?

A difficulty with Shiny apps is also finding the environment to use. I currently reply on pryr::where("r_data") because I know that I defined r_data (and r_state) in the environment I need. Not a great solution but I haven't found a better one.

In case they are interested in this discussion: @wch @jcheng5

**Comment by smbache** [comment] 2015-04-02 19:29
Ok, see this gist: https://gist.github.com/smbache/8c51ec14420bd185cd3a

Your `test.R` would then become:
```R
library(magrittr)

test <- function() {
  
  copy_from(resume, state_init, state_single, state_multiple)
  
  r_state <- list()
  state_init("test") %>% print
  
}

test()
```

**Comment by vnijs** [comment] 2015-04-02 20:24
Nice! Thank you. Any chance this will go into the import package?

Here is where wildcards might be useful, e.g.:

copy_from(resume, state_*)

**Comment by vnijs** [comment] 2015-04-03 01:13
Works great! Thank you. I put your function into [vnijs/radiant](https://github.com/vnijs/radiant/blob/master/R/radiant.R) for now. Hope that is ok. I will replace it with import::copy_from if/when that function makes it into the import package

copy_from(foo, *) might be a nice option as well

**Comment by smbache** [comment] 2015-04-03 05:36
Maybe - I think I need some more use cases/ examples. Can't think of one that doesn't somehow promote "bad practice" ;)

I'm still thinking about the wild cards. One option would be to allow for regex ala `grep`. But one would then need to disregard names in cases of multiple "hits"... Again this could be "misused" to write difficult-to-read code...

**Comment by vnijs** [comment] 2015-04-03 05:52
Your call. I am fine with this solution for now. Thanks again for your help Stefan.

**Comment by smbache** [comment] 2015-04-03 06:28
NP; and thanks for your input and ideas. Let's see what happens.

**Comment by vnijs** [comment] 2015-04-03 07:11
One more (related) question. Could symbol_as_character and symbol_list from the import package be exported? See Note generated during package check for Radiant. 

Unexported objects imported by ':::' calls:
  ‘import:::symbol_as_character’ ‘import:::symbol_list’

**Comment by smbache** [comment] 2015-04-03 07:40
They are not reeally meant for external use; you could just include them in your package too, perhaps? Also they may change if something internal changes and then you'd need to deal with that..

**Comment by vnijs** [comment] 2015-04-03 07:43
Sure. If you don't mind. Thanks

**Comment by smbache** [comment] 2015-04-03 07:48
Of course not :)

**Comment by smbache** [comment] 2015-04-04 18:05
@vnijs FYI you can now specify which library to use when importing. If not specified, `import` will *only* look in the latest specified library (`.libPaths()[1L]`), to remove ambiguity about where a package is found.

**Comment by smbache** [comment] 2015-04-05 18:17
I'll close this for now; still not convinced wild cards are a good idea (although convenient). Let's reopen if someone changes my mind :)

**Closed by smbache** 2015-04-05 18:17 UTC

**Comment by vnijs** [comment] 2015-04-05 18:29
That sounds fine. Thanks Stefan.

**Comment by vnijs** [comment] 2015-11-24 18:50
@smbache Still haven't quite figured out how to get this work the way I need. `copy_all` works fine when the `radiant` package is not loaded. It produces unexpected results, however, when the package is loaded (see discussion linked below). I had hoped that, when the radiant package is loaded, either of the commands below would work to set the environment to the environment created by Shiny. Unfortunately, neither seems to set the environment of functions exported by radiant to the environment I want (i.e., it stays on `package:radiant`). Is there functionality in the `import` package to set the environment for all exported functions in a (loaded) package to a specific environment perhaps?

I'm cc-ing @jcheng5 in case he is willing to comment. 

```r
environment(radiant) <- environment()
environment(radiant) <- new.env(parent = environment())
```

https://groups.google.com/forum/#!topic/shiny-discuss/38EGTG_Y10w
